* 电子书
** 资源
*** http://site.douban.com/109950/widget/notes/250072/note/191427974/
2011-12-22 17:59:32
【推荐】爱问共享资料 （http://ishare.iask.sina.com.cn/）新浪旗下的在线资料分享站，电子书资源丰富，可以按格式搜索。注册即赠送积分，部分电子书下载需要积分，也有很多电子书是骗下载赚积分的，可能只是几个章节，可以先看评论再选择是否下载。搜索kindle电子书的时候可以用“6寸”、“mobi”这样的关键词。 

【推荐】子午书简 （http://book.zi5.me/） 适合kindle用户，是一个站长为分享kindle电子书专门建立的网站，可在线阅读，也可下载epub或mobi格式，亦可推送至kindle。 

【推荐】亿年书海 （http://www.inien.com/） 据说是上海某强人做的，可在线阅读及下载，下载可以选择不同的尺寸及格式，还可自定义格式，功能十分强大。注意下载按钮在导航栏登录注册右边。 

【推荐】Kindle电子书搜索 （http://forfrigg.com/） Kindle电子书搜索引擎，用google自定义搜索制作，这里介绍的网站基本上都有收录，电子书、电子杂志等资源很丰富，可以分格式搜索，很好用。 

【推荐】完美文库（http://www.wmwk.org/） 可在线阅读及下载，可下载txt,mobi,epub格式，亦可投递到kindle。而且移动版可免积分阅读所有内容。积分规则比较复杂。 

【推荐】COAY （http://coay.com/） 提供ePub、mobi格式电子书下载，支持iBooks，Kindle，Stanza等阅读器。 

【推荐】掌上书苑 （http://www.cnepub.com） 下载电子书需要书币，提供epub和mobi格式下载，还可以推送到kindle。 

【推荐】书仓网 （http://shucang.com/） 可在线阅读，提供epub,mobi,pdf等多种格式下载。 

【推荐】皮皮书屋（http://www.ppurl.com/） 收集的书籍专攻计算机科学以及相关延伸学科。大部分是pdf和chm格式，需注册才能查看书籍。注册需要编程基础。可在线浏览及下载（国外IP需申请加入白名单）。 

【推荐】七彩英语 （http://www.qcenglish.com/） 提供英文原版电子书下载，大多为pdf格式，注意有解压密码。 

【推荐】原版图书下载（http://www.cnshare.org/） 英文图书杂志，以计算机及经管励志类书籍为主，其次是原版杂志期刊，大部分书籍是pdf格式。 

【推荐】dogear（http://dogear.mobi/）Kindle看新闻，可下载mobi和epub格式。 

【推荐】ikindle （http://ikindle.mobi/） 每天投递新鲜的报纸和杂志到你的kindle。 

【推荐】kindle4rss （http://kindle4rss.com/） Kindle4RSS是一个让你订阅RSS Feed并定时递送到Kindle的服务。 

———————- 
其它简体电子书网站 
———————- 

苦瓜书盘 （http://kgbook.com/），主要提供6寸pdf以及少量mobi的下载，目前网站因备案问题被关闭。 

苹果电子书 （http://ibook.178.com/） 178旗下网站，提供epub格式电子书下载，适合苹果设备，下载方式比较奇特，点击“找[ta]借阅”即可下载，被借阅次数即下载次数最多的会排在前面。 

书朋网 （http://www.shupeng.com/） 下载链接综合索引自其他网站，如爱问共享资料等。多为txt格式。 

西东网 （http://xidong.net/） 学习资料共享，主要提供教育方面的电子书及其他资料，大多为pdf格式，电驴下载。 

———————- 
其它繁体电子书网站 
———————- 

古登堡计划（中文书籍） （http://www.gutenberg.org/browse/languages/zh） 英文书籍为主，也有部分中文书籍，繁体。 

好读网站 （http://haodoo.net/） 免费的线上繁体中文图书馆，可在线阅读及下载，可下载的格式有：updb，pdb，prc，epub。 

百年千书 （http://1000ebooks.tw/） 百年千书计划，详细介绍请看该网站的“关于我们”或“Q&A”页面。 

———————- 
其它英文电子书网站 
———————- 

feedbooks （http://www.feedbooks.com/） 除了付费书籍外，也提供public domain的书籍和一些新作家免费开放的orginal books，如果想下载免费图书。可点击“Free Public Domain Books”浏览或直接搜索。 

library.nu （http://library.nu/）著名英文电子书下载网站，书籍大部分是pd格式。提供多种网盘下载链接，注意部分文件下载后需要解压密码。 

再分享几个国外电子书网站，不一一介绍了： 
http://avaxhome.ws/ebooks 
http://www.wowebook.com/ 
http://www.ebookee.net/ 
http://ebook3000.com/ 
http://www.ebookshare.net/ 

————————- 
Kindle电子书书目分享 
————————- 

【推荐】Dropbox之Kindle中文电子书 （https://www.dropbox.com/s/b44t0swhzsdlaof） 网友在dropbox中分享的适合kindle阅读的电子书，大部分为mobi格式，部分PRC格式和PDF格式，电子书目录可以下载word版（https://www.dropbox.com/s/b44t0swhzsdlaof/Book%20index%EF%BC%88%E8%AE%BF%E9%97%AE%20irising.me%2C%20%E4%B8%80%E8%B5%B7%E6%B3%A8%E8%A7%A3%E6%95%B0%E5%AD%97%E7%94%9F%E6%B4%BB%EF%BC%89.docx）或者看网页版目录（http://irising.me/2011/05/930/） 

【推荐】skydrive （by young seakye）（https://skydrive.live.com/?cid=ab536aff86b227d2）资源异常丰富，多为pdf格式，分类有CFA、CPA、Economics、Finance、Hacker、IT、Law、psychology、三联哈佛燕京学术丛书、全美经典学习指导系列丛书、剑桥史等等。 

【推荐】txt精排版资源（http://www.hi-pda.com/forum/viewthread.php?tid=569396&extra=page%3D1） 
【推荐】skydrive （by chan jingstone）（https://skydrive.live.com/?cid=65c27572e1ef52ba&id=65C27572E1EF52BA%21125） 同上，资源很丰富，txt精排版。

【推荐】6寸pdf资源 （http://www.hi-pda.com/forum/viewthread.php?tid=483779&extra=page%3D1） 6寸pdf资源汇总。 

————- 
经验及技巧 
————- 

【推荐】HiPDA论坛-Amazon Kindle论坛资源汇总检索帖（http://www.hi-pda.com/forum/viewthread.php?tid=526444&extra=page%3D1&sid=bTuoBx） HiPDA论坛中与Amazon Kindle有关的知识和资源汇总。 

【推荐】Kindle 博文概览（http://irising.me/2011/09/10389/） 一个多人博客，写了很多Kindle方面的博文，文章分为：入手前准备，到手初使用，阅读，上网，折腾，其它等栏目。 

【推荐】kindle 3经验技巧收集汇总（http://www.douban.com/group/topic/19630427/） kindle 3 经验技巧收集汇总。 

———————- 
论坛 
———————- 

HiPDA E-INK论坛 （http://www.hi-pda.com/forum/forumdisplay.php?fid=59） HiPDA论坛的e-ink讨论区，置顶帖里都是精华。 

多看电子书交流 （http://www.duokan.com/forum/forum-16-1.html） Kindle中文系统多看网的电子书交流频道。 

威锋电子书分享 （http://bbs.weiphone.com/thread-htm-fid-224.html） 威锋论坛电子书分享频道，多为epub和pdf格式。 

———————————– 
最后再献上几个电子杂志下载站 
———————————– 

VeryCD（http://www.verycd.com/sto/datum/magazine/） 提供国内外中英文杂志、报纸下载，定期更新，资源丰富。下载方式为电驴。 

Bucee雜誌館（http://bucee.net/） 提供最新简体及繁体中文杂志下载，下载方式为网盘。 

QMAG免費雜誌（http://qmag.org/） 提供最新香港、台灣中文電子雜誌下載，下载方式为网盘。 

原版电子杂志免费下载（http://www.cnrser.com/） 提供最新原版英文杂志下载，下载方式为网盘。 

杂志虫（http://zineworm.com/）外文原版杂志网 ，提供最新原版英文杂志下载，下载方式为网盘。 

媛诺诺时尚杂志馆（http://ynono.com/） 提供日本、韩国、欧美地区原版时尚杂志下载，下载方式为网盘。 

麦根 （http://www.nmag.cn/） 主要提供国内外时尚设计类电子杂志下载。 

免費鏈 （http://freelian.com/） 是一个电子杂志链接收集平台，提供PDF电子杂志下载。 

豆瓣搜索引擎：http://www.doucr.com/ ，搜豆瓣搜不到的东西。
