* jQuery
** 图片上传工具
- jQuery-File-Upload https://github.com/blueimp/jQuery-File-Upload
** 图片编辑
- Jcrop http://deepliquid.com/content/Jcrop.html

** 上传图片前，对图片进行预览
- http://zurb.com/playground/ajax_upload
** 学习资料
- learn jquery http://learn.jquery.com/
** document ready
$(document).ready(function(){
})
** textarea
*** Set value of textarea
$(textareaElement).val()
$(textareaElement).val('aaa')
*** put cursor at end
- 参考: http://stackoverflow.com/questions/511088/use-javascript-to-place-cursor-at-end-of-text-in-text-input-element
input.focus(); //sets focus to element
var val = this.input.value; //store the value of the element
this.input.value = ''; //clear the value of the element
this.input.value = val; //set that value back.

我的做法:
inputElement.on('focus', function(){
  var txt = $(this).val();
  $(this).val('');
  $(this).val(txt);
})

没有试验过:
function moveCursorToEnd(el) {
    if (typeof el.selectionStart == "number") {
        el.selectionStart = el.selectionEnd = el.value.length;
    } else if (typeof el.createTextRange != "undefined") {
        el.focus();
        var range = el.createTextRange();
        range.collapse(false);
        range.select();
    }
}

** 按类遍历DOM
<div class="a">
  <div class="b">
  </div>
</div>

$(".a .b") 或者 $(".a > .b")

** each
- 实例
var ContestFormPrizeStyle = {

    init: function(data){
	this.$ele = $(data.ele);
	this.css_data = data.css_data;

	return this;
    },

    call: function(){
	var _scope = this;

	this.$ele.each(function(i){
	    var img = $(this).attr('src');

	    if(img){
		$(this).css(_scope.css_data);
	    }
	})
    }
}

** ajax
*** 同步请求

	$.ajax({
	    type: 'GET',
	    url: url,
	    data: {heat_sn: this.heat_sn, user_sn: this.user_sn},
	    async: false,
	    success: function(msg){
		vote_result = msg;
	    }
	});

*** 同步调用实例
var VoteResult = {

    init: function(data){
	this.user_sn = data.user_sn;
	this.heat_sn = data.heat_sn

	return this;
    },

    call: function(){
	var vote_result = this.getVoteResult();
	console.log(vote_result);

	if(vote_result.status.resp_code == 0){
	    this.renderVoteResult(vote_result.result);
	    this.fixFit();
	} else {
	    alert(vote_result.resp_msg);
	}
    },

    getVoteResult: function(){
	var vote_result = null;
	var url = '/userVoteResult';

	$.ajax({
	    type: 'GET',
	    url: url,
	    data: {heat_sn: this.heat_sn, user_sn: this.user_sn},
	    async: false,
	    success: function(msg){
		vote_result = msg;
	    }
	});

	return vote_result;
    },

    renderVoteResult: function(vote_result){
	var temp = $("#vote-result-template").html();
	var html = Mustache.render(temp, vote_result);

	$("#vote-result-template").parent().html(html);
    },

    fixFit: function(){
	$(".vote_entities .entity").each(function(i){
	    if((i+1) % 4 == 0)
		$(this).addClass('All_Rank_con1');
	})
    }
}
*** 异步请求实例, done, fail, always
	    $dialog.find('button').on('click', function(){
		var $btn = $(this);
		var $form = $btn.parents('form');
		var url = $form.attr('action');
		var data = $form.serialize();
		var $content = $btn.parents('.Content_Bg');

		_scope.showWait($content);
		_scope.disableBtn($btn);

		$.ajax({
		    type: $form.attr('method') || 'POST',
		    url:   url,
		    data: data
		})
		    .done( function(msg){
			if(msg.status.resp_code != 0){
			    alert(msg.status.resp_msg);
			} else {
			    _scope.removeMainBg();
			    $dialog.parent().remove();
			    // _scope.activeBtn($btn);
			    alert('分享成功');
			    res = msg.result;
			}
		    })
		    .fail(function(msg){
			alert(msg.status + ' 分享失败');
			_scope.activeBtn($btn);
		    })
		    .always(function(){
			_scope.removeWait($content);
		    });

		return false;
	    });

** parents 获取祖先元素
- 实例

var ContestFormPrizeCancel = {

    init: function(data){
	this.$ele = $(data.ele);

	return this;
    },

    call: function(){
	this.$ele.on('click', function(){
	    $(this).parents('.prize_info').remove();
	})
    }

}

** remove event handler
.off
- 实例

** hover
*** 实例01
function($img){
	$img.hover(function(){
	    $(this).parent().css({border: '2px #f73d4b solid'});
	    $(this).siblings('span').hide();
	}, function(){
	    $(this).parent().css({border: 'none'});
	    $(this).siblings('span').hide();
	})
    }

** form
*** 序列化表单参数
$form.serialize();
- 实例
** attributes selector 属性选择器
- 实例
var selected_img_count = $form.find("input[name='images[]']").length;
** 如何编写jQuery插件
- http://ruby-china.org/topics/17159
- http://i5ting.github.io/How-to-write-jQuery-plugin/

** jquery css
$("div").css('width')  #=> 500px
** checkbox

	    this.$btn.on('click', function(){
		if(_scope.$chk.attr('checked') == "checked"){
		    _scope.$chk.attr('checked', null);
		} else {
		    _scope.$chk.attr('checked', 'checked');
		}

		_scope.setIfDefaultRuleChecked();
	    })


ContestForm.SetRuleField = function(data){

    return {

	$ele: $(data.ele),

	init: function(){
	    this.$btn = this.$ele.find('.btnpan');
	    this.$chk = this.$ele.find("input[type='checkbox']");

	    return this;
	},

	call: function(){
	    this.setIfDefaultRuleChecked();
	    this.activeDefaultRuleCheck();
	    return this;
	},

	setIfDefaultRuleChecked: function(){
	    var flag = "create_con_typeon";

	    if(this.$chk.attr("checked") == "checked"){
		if(!this.$btn.hasClass(flag)){
		    this.$btn.addClass(flag);
		}
	    } else {
		if(this.$btn.hasClass(flag)){
		    this.$btn.removeClass(flag);
		}
	    }
	},

	activeDefaultRuleCheck: function(){
	    var _scope = this;

	    this.$btn.on('click', function(){
		if(_scope.$chk.attr('checked') == "checked"){
		    _scope.$chk.attr('checked', null);
		} else {
		    _scope.$chk.attr('checked', 'checked');
		}

		_scope.setIfDefaultRuleChecked();
	    })
	}

    }.init().call();
}

** 获取object本身的html内容
$(".foo").context.outerHTML

** get tag name 获取标签名
- 参考: http://www.mkyong.com/jquery/jquery-how-to-get-the-tag-name/
$('.classTag1').get(0).tagName;
$('.classTag1')[0].tagName;
** 文档操作方法
- 参考: http://www.w3school.com.cn/jquery/jquery_ref_manipulation.asp
*** append
$("button").click(function(){
  $("p").append(" <b>Hello world!</b>");
});
*** appendTo
$("button").click(function(){
  $("<b>Hello World!</b>").appendTo("p");
});
** 动态的开关类 toggleClass
$(".check-btn").on('click', function(){
   $this.toggleClass('Porb2').toggleClass('checked');
 })

** 怎么写jquery插件
(function( $ ){

	$.fn.FloatLabel = function( options ){

		var defaults = {
			populatedClass : 'populated',
			focusedClass : 'focused'
		},
			settings = $.extend({}, defaults, options);

		return this.each(function(){

			var element = $(this),
				label = element.find('label'),
				input = element.find('textarea, input');

      if( input.val() == '' ) {
        input.val( label.text() );
      } else {
        element.addClass( settings.populatedClass );
      }

			input.on( 'focus', function(){
				element.addClass( settings.focusedClass );

				if( input.val() === label.text() ){
					input.val('');
				} else {
					element.addClass( settings.populatedClass );
				}

			});

			input.on( 'blur', function(){
				element.removeClass( settings.focusedClass );

				if( !input.val() ){
					input.val( label.text() );
					element.removeClass( settings.populatedClass );
				}

			});

			input.on( 'keyup', function(){
				element.addClass( settings.populatedClass );
			});

		});

	};

})( jQuery );

$( '.js-float-label-wrapper' ).FloatLabel();

*** 公式
(function($){
  $.fn.xxx = function(){
  };
})(jQuery);

** 刷新页面, refresh page
- 参考: http://stackoverflow.com/questions/5404839/how-can-i-refresh-a-page-with-jquery
$('#something').click(function() {
    location.reload();
});

location.reload(true);
location.reload(false);
true: reload from the server
false: reload from the browser's cache
default is false
** 监测input事件
- http://stackoverflow.com/questions/6458840/on-input-change-event
$('#someInput').bind('input', function() {
    $(this).val() // get the current value of the input field.
});
keyup, keydown
- http://stackoverflow.com/questions/8282266/how-to-prevent-invalid-characters-from-being-typed-into-input-fields

    $("#contest_title").on('keydown', function(e){
	var inputed_str = $(this).val();
	var len = Fchk.Tool.getLengthInBytes(inputed_str);
        // which为8的时候，说明按下的是del键
	if(e.which == 8){return true;}

	return(len < length);
    })


keypress
- http://stackoverflow.com/questions/633876/setting-maxlength-using-javascript

** 文件输入框的change input file
- http://stackoverflow.com/questions/11860721/how-to-handle-onchange-event-on-input-type-file-in-jquery
$("document").ready(function(){
    $("#upload").change(function() {
                alert('changed!');
            });
});

** live 匹配选择器的当前及未来的元素
- http://www.w3school.com.cn/jquery/event_live.asp
$(selector).live(event,data,function)
*** live方法对hover事件的处理
- http://www.oschina.net/code/snippet_54100_3136
*** 代码实例
	    this.$ele.live({
		mouseenter: function(){
		    var $img = $(this).children('img.swf_target');

		    if(!$img.attr('src')){
		    } else {
			$(close_btn_html).appendTo(this).on('click', function(){
			    $img.css({width: 0, height: 0});
			    $img.attr('src', '');
			    $(this).siblings('input').val('');
			    $(this).siblings('p').show();
			    $(this).remove();
			});
		    }

		},
		mouseleave: function(){
		    $(this).children('.board-btn').remove();
		}
	    })

** cookie
- https://github.com/carhartl/jquery-cookie
Create session cookie:

$.cookie('the_cookie', 'the_value');
Create expiring cookie, 7 days from then:

$.cookie('the_cookie', 'the_value', { expires: 7 });
Create expiring cookie, valid across entire site:

$.cookie('the_cookie', 'the_value', { expires: 7, path: '/' });
Read cookie:

$.cookie('the_cookie'); // => "the_value"
$.cookie('not_existing'); // => undefined
Read all available cookies:

$.cookie(); // => { "the_cookie": "the_value", "...remaining": "cookies" }
Delete cookie:

// Returns true when cookie was found, false when no cookie was found...
$.removeCookie('the_cookie');

// Same path as when the cookie was written...
$.removeCookie('the_cookie', { path: '/' });

Delete cookie:

// Returns true when cookie was found, false when no cookie was found...
$.removeCookie('the_cookie');

// Same path as when the cookie was written...
$.removeCookie('the_cookie', { path: '/' });

*** 实例

{
	rememberNoNoticeChecked: function(){
	    var no_notice_checked = $("#no_notice_replay_heat").attr('checked');
	    if(no_notice_checked){
		$.cookie('no_notice_checked', true, { expires: 7, path: '/'});
	    }
	},

	withoutNotice: function(){
	    return $.cookie('no_notice_checked', Boolean);
	}

}

** event.stoppropagation
